// Extract every <style> block from the original single-file HTML app and write
// them, in source order, to app/globals.css. Order matters because many vNNN
// patches rely on cascade position to override earlier rules.
//
// Re-run when the source HTML changes:
//   npm run extract-css

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE_HTML = resolve(
  __dirname,
  '..',
  '..',
  'legal-office-v229-client-detail-mobile-fixed-button-shape.html',
);
const TARGET_CSS = resolve(__dirname, '..', 'app', 'globals.css');

const html = readFileSync(SOURCE_HTML, 'utf8');

// Match <style ...>...</style> blocks (lazy, dot-matches-newline).
const STYLE_RE = /<style(?:\s+([^>]*))?>([\s\S]*?)<\/style>/g;

const chunks = [];
chunks.push('/*');
chunks.push(' * app/globals.css');
chunks.push(' *');
chunks.push(' * Auto-generated from the original single-file HTML app by');
chunks.push(' * scripts/extract-css.mjs. All <style> blocks are concatenated');
chunks.push(' * in source order so the cascade behavior matches the original.');
chunks.push(' *');
chunks.push(' * Do not edit this file by hand. Edit the source HTML and run:');
chunks.push(' *   npm run extract-css');
chunks.push(' */');
chunks.push('');

let count = 0;
let match;
while ((match = STYLE_RE.exec(html)) !== null) {
  const attrs = match[1] || '';
  const css = match[2];
  const idMatch = attrs.match(/id="([^"]*)"/);
  const id = idMatch ? idMatch[1] : '';
  chunks.push(
    `/* ============================================================ *`,
  );
  chunks.push(
    ` * <style${id ? ` id="${id}"` : ''}>`,
  );
  chunks.push(
    ` * ============================================================ */`,
  );
  chunks.push(css.trim());
  chunks.push('');
  count++;
}

writeFileSync(TARGET_CSS, chunks.join('\n'), 'utf8');
console.log(`Extracted ${count} <style> blocks → ${TARGET_CSS}`);
